---
- hosts: localhost
  tasks:
  - name: New VM
    include_role:
      name: esxi

- hosts: dns
  vars:
    coredns_ver: "1.1.3"
  tasks:
  - name: Install and Configure CoreDNS
    include_role:
      name: coredns
    retries: 3
    delay: 3
    become: true
    become_method: sudo
