---
- hosts: masters
  gather_facts: false
  connection: local

  # vars_prompt:
  #   - name: "vcenter_password"
  #     prompt: "vCenter Password"


  tasks:
  - debug: msg="play_hosts={{ play_hosts|length }}"
    run_once: true

  - name: New VM
    include_role:
      name: esxi


# - hosts: dns
#   vars:
#     coredns_ver: "1.4.0"
#     ansible_become_pass: "{{ pass }}"
#   tasks:
#   - name: Install and Configure CoreDNS
#     include_role:
#       name: coredns
#     retries: 3
#     delay: 3
#     become: true
#     become_method: sudo