---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name:  Clone Machine
    vmware_guest:
      hostname: 192.168.50.50
      username: Administrator@kennedy.land
      password: "{{ vcenter_password }}"
      esxi_hostname: 192.168.0.50
      validate_certs: no
      state: present
      folder: /
      template: Ubuntu18.04
      name: CoreDNS
      datacenter: Datacenter
      networks:
        - name: VM Network
          ip: 192.168.50.100
          netmask: 255.255.255.0
          gateway: 192.168.50.1
      wait_for_ip_address: True
      customization:
        hostname: testvm
        dns_servers:
          - 8.9.9.9
          - 7.8.8.9
        dns_suffix:
          - kennedy.land
    register: newvm
    delegate_to: localhost

  - name: IP address info
    debug:
      msg: "{{ newvm.instance.ipv4 }} {{ name }}"