---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name:  Clone a virtual machine from Linux template and customize
    vmware_guest:
      hostname: 192.168.50.50
      username: Administrator@kennedy.land
      password: "{{ vcenter_password }}"
      esxi_hostname: 192.168.0.50
      validate_certs: no
      state: present
      folder: /
      template: CoreDNS
      name: testVM
      datacenter: Datacenter
      networks:
        - name: VM Network
          ip: 192.168.50.120
          netmask: 255.255.255.0
      wait_for_ip_address: True
      customization:
        dns_servers:
          - 8.9.9.9
          - 7.8.8.9
        dns_suffix:
          - kennedy.land
    delegate_to: localhost