---
- hosts: localhost
  vars:
    vcenter_folder: infra
    host_template: Ubuntu18.04
    vm_name: store
    vm_memory_mb: 4096
    vm_cpus: 2
    vm_network: VM Network
    vm_ip: 192.168.50.102
    vm_netmask: 255.255.255.0
    vm_gateway: 192.168.50.1
    vm_dns_1: 192.168.50.100
    vm_dns_2: 8.8.8.8
    dns_suffix: kennedy.land
    group: store
    memory_reservation_lock: true
  tasks:
  - name: New VM
    include_role:
      name: esxi

- hosts: store
  vars:
    ansible_become_pass: "{{ pass }}"
    iscsi_user: "{{ iscsi_user }}"
    iscsi_pass: "{{ iscsi_pass }}"
  tasks:
  - name: Install and configure ZFS
    include_role:
      name: zfs
    retries: 3
    delay: 3
    become: true
    become_method: sudo

# - hosts: zfs
#   vars:
#     ansible_become_pass: "{{ pass }}"
#   tasks:
#   - name: Install and configure NFS
#     include_role:
#       name: nfs
#     retries: 3
#     delay: 3
#     become: true
#     become_method: sudo

# - hosts: zfs
#   vars:
#     ansible_become_pass: "{{ pass }}"
#   tasks:
#   - name: Install and configure samba share
#     include_role:
#       name: smb
#     retries: 3
#     delay: 3
#     become: true
#     become_method: sudo

# - hosts: zfs
#   vars:
#     ansible_become_pass: "{{ pass }}"
#   tasks:
#   - name: Install and configure iSCSI
#     include_role:
#       name: iscsi
#     retries: 3
#     delay: 3
#     become: true
#     become_method: sudo