---
- name: Create VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ esxi_hostname }}"
    validate_certs: no
    state: present
    folder: "{{ vcenter_folder }}"
    template: "{{ host_template }}"
    name: "{{ inventory_hostname }}"
    datacenter: "{{ host_datacenter }}"
    disk:
    - size_gb: "{{ disk_size_gb }}"
      type: thin
      datastore: "{{ host_datastore }}"
    hardware:
        #memory_reservation_lock: "{{ memory_reservation_lock }}"
        memory_mb: "{{ vm_memory_mb }}"
        mem_limit: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_cpus }}"
    networks:
      - name: "{{ vm_network }}"
        ip: "{{ custom_ip }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
    wait_for_ip_address: True
    customization:
      hostname: "{{ inventory_hostname }}"
      dns_servers:
        - "{{ vm_dns_1 }}"
        - "{{ vm_dns_2 }}"
      dns_suffix:
        - "{{ dns_suffix }}"
  register: "{{ inventory_hostname }}"
  delegate_to: localhost


# - name: Dynamically add newly created VM to the inventory
#   add_host:
#     hostname: "{{ vm_ip }}"
#     groups: "{{ group }}"
#     ansible_ssh_user: nkennedy
#     ansible_ssh_pass: "{{ pass }}"
