---
- name: Uninstall previous versions
  become: yes
  apt:
    pkg: "{{item}}"
    state: absent
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
    - containerd.io

- name: Install repository packages
  become: yes
  apt:
    pkg: "{{item}}"
    state: latest
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg-agent

- name: Add docker's official GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Setup stable docker-ce repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present

- name: Install docker-ce
  become: yes
  apt:
    name: "docker-ce={{ docker_version }}"
    state: "present"
    update_cache: yes
  notify:
    - restart docker

- name: Run docker-ce as a service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to the docker system group
  become: yes
  user:
    name: "{{ item }}"
    groups: "{{ docker_group }}"
    append: yes
  with_items: "{{ docker_users }}"